docs: Add details to GitOps deployment tools integration
keptn/community pull request #172
Opened 2022-09-21 18:53 UTC by mehabhalodiya

Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>

Regarding the GSoC Project page update
cc: @oleg-nenashev @bradmccoydev @thschue

2022-09-21 22:36 UTC, basiq-brad approved these changes

2022-09-21 22:38 UTC, bradmccoydev approved these changes

2022-09-22 05:01 UTC, oleg-nenashev requested changes
It is a good improvement but it still does not meet the GSoC requirements. It is expected that the links are provided to all created code and contributions. There is only a link to https://github.com/keptn-sandbox/keptn-flux-integration, but it has no contributions since July 27th

2022-10-04 08:51 UTC, oleg-nenashev approved these changes
I am merging it as is due to the lack of response from @mehabhalodiya and mentors.

2022-10-04 08:51 UTC, merged