Create GC and TC members and charter
keptn/community pull request #253
Opened 2023-03-17 11:50 UTC by DavidPHirsch

Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>

2023-03-22 11:06 UTC, AloisReitbauer requested changes
we should just provide the names for GC members and probably the GH handle

2023-04-01 05:16 UTC, agardnerIT commented
The technical committee sounds potentially interesting. What is the charter / AOR?

@bradmccoydev and I were talking about this the other day. Interestingly Brad has already had a lot of support for him to join the TC: https://github.com/keptn/community/issues/238

2023-04-24 18:30 UTC, thschue commented on governance/members-and-charter.md
> +
```suggestion
@thschue 
```

2023-06-20 08:32 UTC, DavidPHirsch commented
@AlexsJones @AloisReitbauer @AnaMMedina21 could you please review this issue?

2023-06-20 08:44 UTC, AlexsJones commented on governance/members-and-charter.md
> + Maintain relationships with the CNCF. For instance, creating documents describing the project
Missing a full stop at the end. 

Generally it's quite a busy paragraph, might want to break it down a bit for readability

2023-06-20 08:44 UTC, AlexsJones commented on governance/members-and-charter.md
> + - Personal Website: https://www.cloudnativeskunkworks.io/
Please remove website, it's no longer used

2023-06-21 16:46 UTC, AnaMMedina21 approved these changes

2023-07-03 14:38 UTC, merged